pipeline {
    agent {
        label 'main'
    }
    stages {
        stage("ls") {
            steps {
                script {
                    sh "ls"
                }
            }
        }
        stage("mvn clean") {
            steps {
                script {
                    sh "mvn clean package"
                }
            }
        }
        // stage("docker build test") {
        //     steps {
        //         script {
        //             sh "cp ./jenkins/Dockerfile ./Dockerfile"
        //             sh "docker build -t petclinic ."
        //         }
        //     }
        // }
        stage("docker build docker image and push to ecr") {
        	steps {
                script {
                    sh 'docker image prune -a -f'
                    sh "cp ./jenkins/Dockerfile ./Dockerfile"
                    TAG = sh (
                        script: 'git log -1 --pretty=%h',
                        returnStdout: true
                    ).trim()
                    docker.withRegistry(
                        'https://934086672967.dkr.ecr.eu-central-1.amazonaws.com',
                        'ecr:eu-central-1:aws_creds') {
                            def myImage = docker.build('java')
                        myImage.push(TAG)
                    }
                }
            }
        }
    }
}